### ISSUE TITLE
Time for a move?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby-pkgs#18]
@larskanis, @hsbt, @eregon

Thought I'd ping everyone about the idea of moving this repo to the Ruby org.  It performs package installation across all Actions platforms, and uses the code from ruby/setup-ruby to perform all of setup-ruby's operations.  Cross-platform example:

```yml
- name: Set up Ruby & Ragel
  uses: MSP-Greg/setup-ruby-pkgs@v1
  with:
    ruby-version: ${{ matrix.ruby }}
    apt-get: ragel
    brew: ragel
    mingw: ragel
```

Additionally, it has all the logic needed for Windows package installation.  Now that current Rubies use both the mingw64 and ucrt64 MSYS2 toolsets, the names of the packages are dependent on the toolset used.

If one has simple CI requirements where the OS is part of the matrix, this action simplifies the number of steps needed to install a package, regardless of OS.

Thoughts?
